const EErros = {
    ROUTING_ERROR: 1,
    INVALID_TYPES_ERROR: 2,
    DATABASES_ERROR: 3,
    USER_EXISTS_ERROR:4,
    EMAIL_NOT_FOUND_ERROR:5,
    INVALID_PASSWORD_ERROR:6,
    USER_NOT_FOUND_ERROR:7,
    CART_NOT_FOUND_ERROR:8,
    PRODUCT_NOT_FOUND_ERROR:9,
  };
  
  export default EErros;