const EErros = {
    ROUTING_ERROR: 1,
    INVALID_TYPES_ERROR: 2,
    DATA_BASE_ERROR: 3,
    USER_EXISTS_ERROR:4,
    EMAIL_NOT_FOUND_ERROR:5,
    INVALID_PASSWORD_ERROR:6,
    USER_NOT_FOUND_ERROR:7,
    CART_NOT_FOUND_ERROR:8,
    PRODUCT_NOT_FOUND_ERROR:9,
    CART_NOT_CREATED_ERROR:10,
    INVALID_CREDENTIALS_ERROR:11,
    UNAUTHORIZED_PRODUCT_DELETION_ERROR:12,
    PRODUCT_CODE_ALREADY_EXISTS_ERROR:13,
    USER_NOT_CREATED:14,
  };
  
  export default EErros;